---

- name: analyzer | Download runner
  get_url: 
    url="{{sonar_analyzer_runner_url}}"
    dest="/tmp/{{sonar_analyzer_runner_file}}"
  tags: sonar_setup

- name: analyzer | Create base dir runner
  file: 
    dest="{{sonar_analyzer_runner_dir}}"
    state=directory
    owner="{{sonar_owner}}"
    group="{{sonar_group}}"
  tags: sonar_setup

- name: analyzer | Extract runner archive
  unarchive: 
    src="/tmp/{{sonar_analyzer_runner_file}}"
    dest="{{sonar_base_dir}}/"
    owner="{{sonar_owner}}"
    group="{{sonar_group}}"
    copy=no
    creates="{{sonar_analyzer_runner_dir}}/conf"
  notify: restart sonar
  sudo_user: "{{sonar_owner}}"
  tags: sonar_setup

- name: analyzer | Configure runner
  template:
    src=sonar-runner.properties.j2
    dest="{{sonar_analyzer_runner_dir}}/conf/sonar-runner.properties"
  tags: sonar_setup
  notify: restart sonar

- name: analyzer | bash profile SONAR_RUNNER_HOME
  lineinfile: 
     dest="{{sonar_base_dir}}/.bash_profile" 
     state=present
     create=yes
     regexp="SONAR_RUNNER_HOME"
     line="export SONAR_RUNNER_HOME={{sonar_analyzer_runner_version}}"
     mode=0644
     owner="{{sonar_owner}}"
     group="{{sonar_group}}"

- name: analyzer | bash profile PATH
  lineinfile: 
     dest="{{sonar_base_dir}}/.bash_profile" 
     state=present
     create=yes
     regexp="PATH"
     line="export PATH=$PATH:{{sonar_analyzer_runner_version}}"
     mode=0644
     owner="{{sonar_owner}}"
     group="{{sonar_group}}"     