---

- include: sonar.yml

- include: analyzer_runner.yml
  when: sonar_analyzer_runner_install
  
- include: lang_py.yml
  when: sonar_analyzer_py_install

- include: maven.yml
  when: maven_install

- include: projects.yml
  when: sonar_projects is defined